name: dered
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - archspec=0.2.3=pyhd8ed1ab_0
  - boltons=24.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.3=heb4867d_0
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=24.7.1=py311h38be061_0
  - conda-libmamba-solver=24.9.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_0
  - conda-package-streaming=0.11.0=pyhd8ed1ab_0
  - cpp-expected=1.1.0=hf52228f_0
  - distro=1.9.0=pyhd8ed1ab_0
  - fmt=10.2.1=h00ab1b0_0
  - frozendict=2.4.6=py311h9ecbd09_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_0
  - ilmbase=2.5.5=h780b84a_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h38be061_1
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libarchive=3.7.4=hfca40fe_0
  - libcurl=8.8.0=hca28451_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libmamba=1.5.8=had39da4_0
  - libmambapy=1.5.8=py311hf2555c7_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libsolv=0.7.29=ha6fb4c9_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h7b6447c_2
  - mamba=1.5.8=py311h3072747_0
  - menuinst=2.2.0=py311h38be061_0
  - ncurses=6.4=h6a678d5_0
  - nlohmann_json=3.11.3=he02047a_1
  - openexr=2.5.5=hf817b99_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhff2d567_1
  - pip=24.2=py311h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311h459d7ec_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.8=hab00c5b_0_cpython
  - python_abi=3.11=5_cp311
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=pyhd8ed1ab_0
  - ruamel.yaml=0.18.6=py311h9ecbd09_1
  - ruamel.yaml.clib=0.2.8=py311h9ecbd09_1
  - setuptools=75.1.0=py311h06a4308_0
  - simdjson=3.10.1=h84d6215_0
  - spdlog=1.14.1=h597fd29_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.13=noxft_h4845f30_101
  - truststore=0.10.0=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py311hbc35293_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - click==8.1.7
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.16.1
      - fonttools==4.55.0
      - fsspec==2024.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h5py==3.12.1
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - markupsafe==3.0.2
      - mat73==0.65
      - matplotlib==3.5.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.7.0.72
      - pandas==2.2.3
      - pathtools==0.1.2
      - pillow==11.0.0
      - promise==2.3
      - protobuf==3.20.3
      - psutil==6.1.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - scipy==1.9.3
      - sentry-sdk==2.18.0
      - setproctitle==1.3.4
      - shortuuid==1.0.13
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.13.1
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.64.1
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - wandb==0.12.21
